#!/usr/bin/env python3
"""Generate a UV sphere OBJ centered at origin, shared by both the lightrt and
the ASF MaterialX reference renderers so geometry is never a variable in the
comparison. Positions + per-vertex normals + lat-long UVs.

Default radius is 2/sqrt(3) ~= 1.1547, NOT 1. MaterialXView normalizes any mesh
to a fixed effective sphere radius of IDEAL_MESH_SPHERE_RADIUS(2.0) /
bbox_corner_dist = 2/(R*sqrt(3))*R = 2/sqrt(3), independent of the input scale,
then renders it with camera (0,0,5) / fov_y 45deg. Making the actual sphere this
radius means lightrt (which uses the true radius) projects it identically, so
the two renders frame the sphere pixel-for-pixel without any post-registration.

Usage:  python3 gen_sphere.py [out.obj] [u_segments] [v_segments] [radius]
"""
import math
import sys

out = sys.argv[1] if len(sys.argv) > 1 else "sphere.obj"
U = int(sys.argv[2]) if len(sys.argv) > 2 else 128   # longitude
V = int(sys.argv[3]) if len(sys.argv) > 3 else 64    # latitude
R = float(sys.argv[4]) if len(sys.argv) > 4 else 2.0 / math.sqrt(3.0)  # MaterialXView framing

verts, norms, uvs, faces = [], [], [], []

# Grid of (V+1) x (U+1) vertices; poles duplicated across the seam for clean UVs.
for j in range(V + 1):
    v = j / V
    theta = v * math.pi          # 0..pi  (north pole -> south pole)
    st, ct = math.sin(theta), math.cos(theta)
    for i in range(U + 1):
        u = i / U
        phi = u * 2.0 * math.pi  # 0..2pi
        sp, cp = math.sin(phi), math.cos(phi)
        x, y, z = st * cp, ct, st * sp
        verts.append((R * x, R * y, R * z))
        norms.append((x, y, z))  # unit normal == position / R
        uvs.append((u, 1.0 - v))

def idx(i, j):
    return j * (U + 1) + i + 1   # OBJ is 1-based

for j in range(V):
    for i in range(U):
        a, b, c, d = idx(i, j), idx(i + 1, j), idx(i + 1, j + 1), idx(i, j + 1)
        # two triangles per quad, skipping degenerate ones at the poles
        if j != 0:
            faces.append((a, b, d))
        if j != V - 1:
            faces.append((b, c, d))

with open(out, "w") as f:
    f.write("# UV sphere (radius %.6f) for the MaterialX verify harness\n" % R)
    f.write("# generated by verify/assets/gen_sphere.py\n")
    for x, y, z in verts:
        f.write("v %.6f %.6f %.6f\n" % (x, y, z))
    for u, w in uvs:
        f.write("vt %.6f %.6f\n" % (u, w))
    for x, y, z in norms:
        f.write("vn %.6f %.6f %.6f\n" % (x, y, z))
    for a, b, c in faces:
        f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, b, b, b, c, c, c))

print("wrote %s: %d verts, %d tris" % (out, len(verts), len(faces)))
